### ISSUE TITLE
AttributeError: 'TextRedirector' object has no attribute 'flush'

### ISSUE THREAD

**Issue by 0yz** [KILLTUBE/corvid#11] opened 2021-04-23 10:43 UTC
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
  File "app.py", line 410, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 481, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 314, in createMaterialGdt
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 409, in createMaterialGdtBo3
TypeError: replace expected at least 2 arguments, got 0
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-1, started 3692)>>
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908, in _bootstrap
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 952, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1220, in invoke_excepthook
AttributeError: 'TextRedirector' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'TextRedirector' object has no attribute 'flush'
```

I get this error often with different types of maps hl2/csgo/sourcemods.
What does this mean? What is the issue?

_btw thanks for this project, i love it!_

**Comment by myuce** [comment] 2021-04-24 02:30
You'll see the `TextRedirector` error whenever the program bumps into an issue. It would be really nice if you share the entire console log and told me the name of the map so I can test it myself and see what the problem is about.

**Comment by 0yz** [comment] 2021-04-24 08:34
sorry, here is for example the full log when i try to convert "ep2_outland_10" from HL2:EP2

`Opening VMF file "X:\BO3 Tools\_CONVERTEDMAPS\ep2_outland_10_d.vmf"...
Reading VMF file...
3d sky box not selected. It will be converted as a smaller version of itself...
Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_pak_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_misc_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_textures_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/ep2/ep2_pak_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_textures_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_misc_dir.vpk...
Mounting D:/Steam/steamapps/common/half-life 2/ep2...
Mounting D:/Steam/steamapps/common/half-life 2/hl2...
Loading materials...
Loading texture data...
Extracting models...
Loading model materials...
Generating GDT file...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
  File "app.py", line 410, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 481, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 314, in createMaterialGdt
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 409, in createMaterialGdtBo3
TypeError: replace expected at least 2 arguments, got 0
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-2, started 9960)>>
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908, in _bootstrap
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 952, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1220, in invoke_excepthook
AttributeError: 'TextRedirector' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'TextRedirector' object has no attribute 'flush'`

**Comment by 0yz** [comment] 2021-04-24 08:34
> Opening VMF file "X:\BO3 Tools\\_CONVERTEDMAPS\ep2_outland_10_d.vmf"...
> Reading VMF file...
> 3d sky box not selected. It will be converted as a smaller version of itself...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_pak_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_misc_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_textures_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/ep2/ep2_pak_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_textures_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2/hl2_misc_dir.vpk...
> Mounting D:/Steam/steamapps/common/half-life 2/ep2...
> Mounting D:/Steam/steamapps/common/half-life 2/hl2...
> Loading materials...
> Loading texture data...
> Extracting models...
> Loading model materials...
> Generating GDT file...
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
>   File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
>   File "app.py", line 410, in convertButton_command
>   File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 481, in exportMap
>   File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 314, in createMaterialGdt
>   File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 409, in createMaterialGdtBo3
> TypeError: replace expected at least 2 arguments, got 0
> Exception in threading.excepthook:
> Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-2, started 9960)>>
> Traceback (most recent call last):
>   File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908, in _bootstrap
>   File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 952, in _bootstrap_inner
>   File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1220, in invoke_excepthook
> AttributeError: 'TextRedirector' object has no attribute 'flush'
> Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
> AttributeError: 'TextRedirector' object has no attribute 'flush'


This is for example the full log for the map "ep2_outland_10" from HL2:EP2.
I'm using the latest version of Bspsrc to decompile. [Here is the vmf file.](https://mega.nz/file/FppiUQoC#Z-bv8Xb2Jyfv0WiyBd2j3aA5-r6RIxlzuf7lMUcETdY)

**Comment by snowtyler** [comment] 2021-04-25 21:06
I seem to run into this error a lot as well. Here's my most recent attempt with d1_eli_01 from HL2.
[Corvid-log-25.04.2021_(16.56.46).txt](https://github.com/KILLTUBE/corvid/files/6373008/Corvid-log-25.04.2021_.16.56.46.txt)

I will also attach the vmf.
https://mega.nz/file/l3YSFBya#Utypor3sTtLLlM6xEHzMkufQLigsRmwyDEfBrxbvJuM

**Comment by myuce** [comment] 2021-05-03 06:19
Sorry for the delay, but it should be fixed after the latest commits. You can safely convert those maps with the latest version of Corvid.

**Closed as completed** 2021-05-03 06:20 UTC
